{{- if eq .Values.mode "cluster" }}
{{ $name := include "arangodb.coordinator.fullname" . }}
{{ $serviceName := printf "%s-internal" (include "arangodb.coordinator.fullname" .)  }}
{{ $agentName := include "arangodb.agent.fullname" . }}
{{ $agentServiceName := printf "%s-internal" (include "arangodb.agent.fullname" .)  }}
{{ $replicas := .Values.coordinator.replicas }}
{{ $serverContainerPort := 8529 }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $name }}
  labels:
    {{- include "arangodb.coordinator.labels" . | nindent 4 }}
spec:
  serviceName: {{ $serviceName }}
  replicas: {{ $replicas }}
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      {{- include "arangodb.coordinator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.global.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "arangodb.coordinator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "arangodb.serviceAccountName" . }}
      volumes:
        - name: data
          emptyDir: {}
        - name: lifecycle
          emptyDir: {}
        {{- if not .Values.auth.jwtSecret.existingFile }}
        - name: cluster-jwt
          secret:
            defaultMode: 420
            secretName: {{ include "arangodb.jwtSecret.secretName" . }}
        {{- end }}
      initContainers:
        - name: init-lifecycle
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/bin/arangodb_operator
            - lifecycle
            - copy
            - '--target'
            - /lifecycle/tools
          volumeMounts:
            - mountPath: /lifecycle/tools
              name: lifecycle
        - name: init-uuid
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - >-
              /lifecycle/tools/arangodb_operator uuid
              --uuid-path /data/UUID
              --engine-path /data/ENGINE
              --uuid CRDN-$(echo -n "$MY_POD_NAMESPACE-$MY_POD_NAME" | sha1sum | awk '{print $1}')
              --engine rocksdb
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /lifecycle/tools
              name: lifecycle
      containers:
        - name: server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - '/usr/sbin/arangod'
            - '--cluster.my-role=COORDINATOR'
            {{- range untilStep 0 (int .Values.agent.replicas) 1 }}
            - '--cluster.agency-endpoint=tcp://{{ $agentName }}-{{ . }}.{{ $agentServiceName }}:8531'
            {{- end }}
            - '--cluster.my-address=tcp://$(MY_POD_NAME).{{ $serviceName }}:8529'
            - '--server.endpoint=tcp://[::]:8529'
            - '--server.authentication=true'
            - '--server.jwt-secret-keyfile={{ include "arangodb.jwtSecret.path" . }}'
            - '--database.directory=/data'
          lifecycle:
            preStop:
              exec:
                command:
                  - /lifecycle/tools/arangodb_operator
                  - lifecycle
                  - preStop
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /lifecycle/tools
              name: lifecycle
            {{- if not .Values.auth.jwtSecret.existingFile }}
            - mountPath: {{ include "arangodb.jwtSecret.mountPath" . }}
              name: cluster-jwt
            {{- end }}
          ports:
            - containerPort: 8529
              name: server
              protocol: TCP
          env:
            - name: ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY
              valueFrom:
                resourceFieldRef:
                  containerName: server
                  resource: limits.memory
            - name: ARANGODB_OVERRIDE_DETECTED_NUMBER_OF_CORES
              valueFrom:
                resourceFieldRef:
                  containerName: server
                  resource: limits.cpu
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources:
            {{- toYaml .Values.coordinator.resources | nindent 12 }}
      {{- include "imagePullSecrets" . | nindent 6 }}
{{- end }}
